# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discount_validproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='validProducts',
            field=models.ManyToManyField(blank=True, help_text='Make sure not to include gift certificates!', to='product.Product', verbose_name='Valid Products'),
        ),
    ]
