# Generated by Django 2.1.7 on 2019-04-01 19:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20180519_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter absolute discount amount OR percentage.  Percentage example: "0.10".', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('1.0')), django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Discount Percentage'),
        ),
    ]
