# Generated by Django 2.1.7 on 2019-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20190401_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='site',
        ),
    ]
