# Generated by Django 2.1.7 on 2019-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0006_auto_20180519_1533")]

    operations = [migrations.RemoveField(model_name="brand", name="site")]
