# Generated by Django 2.1.7 on 2019-04-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_remove_brand_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='Full description, visible to customers'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='brand/', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short Description'),
        ),
    ]
