# Generated by Django 2.1.7 on 2019-04-24 14:35

from django.db import migrations


def reduce_translations(apps, schema_editor):
    Brand = apps.get_model("brand", "Brand")
    for brand in Brand.objects.all():
        translation = brand.translations.first()
        if translation:
            if translation.name:
                brand.name = translation.name
            if translation.short_description:
                brand.short_description = translation.short_description
            if translation.meta_description:
                brand.meta_description = translation.meta_description
            if translation.description:
                brand.description = translation.description
            if translation.picture:
                brand.picture = translation.picture
            brand.save()


class Migration(migrations.Migration):

    dependencies = [("brand", "0008_auto_20190424_1434")]

    operations = [migrations.RunPython(reduce_translations)]
