# Generated by Django 2.1.7 on 2019-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180519_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for quantity of 1', max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
