# Generated by Django 2.1.7 on 2019-04-01 19:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0007_auto_20190401_1903")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Base price for quantity of 1",
                max_digits=10,
                verbose_name="Unit Price",
            ),
        )
    ]
