# Generated by Django 2.1.7 on 2019-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190401_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'ordering', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('ordering', 'name'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='site',
        ),
        migrations.RemoveField(
            model_name='optiongroup',
            name='site',
        ),
        migrations.RemoveField(
            model_name='productpricelookup',
            name='siteid',
        ),
        migrations.AlterField(
            model_name='price',
            name='quantity',
            field=models.IntegerField(default=2, help_text='Use this price only for this quantity or higher', verbose_name='Discount Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for URLs, auto-generated from name if blank', max_length=80, unique=True, verbose_name='Slug Name'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='site',
        ),
    ]
