# Generated by Django 2.1.7 on 2019-04-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190415_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Optional caption'),
        ),
        migrations.AlterField(
            model_name='customtextfield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Custom field name'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Display value'),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Stored value'),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='description',
            field=models.TextField(blank=True, help_text='Further description of this group (i.e. shirt size vs shoe size).', verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='name',
            field=models.CharField(help_text='This will be the text displayed on the product page.', max_length=255, verbose_name='Name of Option Group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The products full name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for URLs, auto-generated from name if blank', max_length=255, unique=True, verbose_name='Slug Name'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Optional caption'),
        ),
    ]
