# Generated by Django 2.1.7 on 2019-04-24 13:15

from django.db import migrations


def reduce_translations(apps, schema_editor):
    Category = apps.get_model("product", "Category")
    for category in Category.objects.all():
        translation = category.translations.filter(active=True).first()
        if translation:
            if translation.name:
                category.name = translation.name
            category.save()

    CategoryImage = apps.get_model("product", "CategoryImage")
    for category_image in CategoryImage.objects.all():
        translation = category_image.translations.filter(active=True).first()
        if translation:
            if translation.caption:
                category_image.caption = translation.caption
            category_image.save()

    CustomTextField = apps.get_model("product", "CustomTextField")
    for custom_text_field in CustomTextField.objects.all():
        translation = custom_text_field.translations.filter(active=True).first()
        if translation:
            if translation.name:
                custom_text_field.name = translation.name
            custom_text_field.save()

    Option = apps.get_model("product", "Option")
    for option in Option.objects.all():
        translation = option.translations.filter(active=True).first()
        if translation:
            if translation.name:
                option.name = translation.name
            if translation.value:
                option.value = translation.value
            option.save()

    OptionGroup = apps.get_model("product", "OptionGroup")
    for option_group in OptionGroup.objects.all():
        translation = option_group.translations.filter(active=True).first()
        if translation:
            if translation.name:
                option_group.name = translation.name
            if translation.description:
                option_group.description = translation.description
            option_group.save()

    Product = apps.get_model("product", "Product")
    for product in Product.objects.all():
        translation = product.translations.filter(active=True).first()
        if translation:
            if translation.name:
                product.name = translation.name
            if translation.slug:

                product.slug = translation.slug
            product.save()

    ProductImage = apps.get_model("product", "ProductImage")
    for product_image in ProductImage.objects.all():
        translation = product_image.translations.filter(active=True).first()
        if translation:
            if translation.caption:
                product_image.caption = translation.caption
            product_image.save()


class Migration(migrations.Migration):

    dependencies = [("product", "0010_auto_20190424_1315")]

    operations = [migrations.RunPython(reduce_translations)]
