# Generated by Django 2.1.7 on 2019-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190424_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryimagetranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categoryimagetranslation',
            name='categoryimage',
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='customtextfieldtranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customtextfieldtranslation',
            name='customtextfield',
        ),
        migrations.AlterUniqueTogether(
            name='optiongrouptranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='optiongrouptranslation',
            name='optiongroup',
        ),
        migrations.AlterUniqueTogether(
            name='optiontranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='optiontranslation',
            name='option',
        ),
        migrations.AlterUniqueTogether(
            name='productimagetranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productimagetranslation',
            name='productimage',
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='languagecode',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='This field can contain HTML and should be a few paragraphs explaining the background of the product, and anything that would help the potential customer make their purchase.', verbose_name='Description of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='This should be a 1 or 2 line description for use in product listing screens', max_length=200, verbose_name='Short description of product'),
        ),
        migrations.DeleteModel(
            name='CategoryImageTranslation',
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
        migrations.DeleteModel(
            name='CustomTextFieldTranslation',
        ),
        migrations.DeleteModel(
            name='OptionGroupTranslation',
        ),
        migrations.DeleteModel(
            name='OptionTranslation',
        ),
        migrations.DeleteModel(
            name='ProductImageTranslation',
        ),
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
