# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20160728_2034'),
        ('tieredweightzone', '0001_initial'),
    ]
    # Fake tieredweightzone1
    operations = [
        # migrations.RemoveField(
        #     model_name='carriertranslation',
        #     name='carrier',
        # ),
        # migrations.RemoveField(
        #     model_name='shippingdiscount',
        #     name='carrier',
        # ),
        # migrations.RemoveField(
        #     model_name='shippingdiscount',
        #     name='zone',
        # ),
        # migrations.RemoveField(
        #     model_name='weighttier',
        #     name='carrier',
        # ),
        # migrations.RemoveField(
        #     model_name='weighttier',
        #     name='zone',
        # ),
        # migrations.RemoveField(
        #     model_name='zone',
        #     name='continent',
        # ),
        # migrations.RemoveField(
        #     model_name='zone',
        #     name='country',
        # ),
        # migrations.RemoveField(
        #     model_name='zonetranslation',
        #     name='zone',
        # ),
        # migrations.DeleteModel(
        #     name='Carrier',
        # ),
        # migrations.DeleteModel(
        #     name='CarrierTranslation',
        # ),
        # migrations.DeleteModel(
        #     name='ShippingDiscount',
        # ),
        # migrations.DeleteModel(
        #     name='WeightTier',
        # ),
        # migrations.DeleteModel(
        #     name='Zone',
        # ),
        # migrations.DeleteModel(
        #     name='ZoneTranslation',
        # ),
    ]
