# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20160728_2034'),
        ('tieredweightzone', '0001_initial'),
    ]
    # Fake tieredweightzone1
    operations = [
    ]
