# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20170214_0926'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='exchangerate',
            order_with_respect_to=None,
        ),
    ]
