# Generated by Django 2.1.7 on 2019-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("configuration", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(
            name="longsetting", unique_together={("group", "key")}
        ),
        migrations.RemoveField(model_name="longsetting", name="site"),
        migrations.AlterUniqueTogether(
            name="setting", unique_together={("group", "key")}
        ),
        migrations.RemoveField(model_name="setting", name="site"),
    ]
