# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.db import migrations, models
import satchmo.payment.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170508_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('In Person', 'In Person'), ('Show', 'Show')], max_length=200, verbose_name='Order method'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='payment',
            field=satchmo.payment.fields.PaymentChoiceCharField(blank=True, max_length=25),
        ),
    ]
