# Generated by Django 2.1 on 2018-08-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180823_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Transaction ID'),
        ),
    ]
