# Generated by Django 2.1.7 on 2019-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180903_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='site',
        ),
        migrations.RemoveField(
            model_name='order',
            name='site',
        ),
        migrations.AlterField(
            model_name='config',
            name='no_stock_checkout',
            field=models.BooleanField(default=False, verbose_name='Purchase item not in stock?'),
        ),
    ]
