# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('l10n', '0003_auto_20180519_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(verbose_name='Key')),
                ('ordering', models.IntegerField(default=0, verbose_name='Ordering')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('signed_for', models.BooleanField(default=False, verbose_name='Signed For')),
                ('tracked', models.BooleanField(default=False, verbose_name='Tracked')),
                ('postage_speed', models.PositiveIntegerField(choices=[(0, 'Urgent'), (1, 'Priority'), (2, 'Standard'), (3, 'Economy')], default=2, verbose_name='Postage Speed')),
                ('estimated_delivery_min_days', models.PositiveIntegerField(default=1, verbose_name='Minimum number of days after shipping until delivery')),
                ('estimated_delivery_expected_days', models.PositiveIntegerField(default=7, verbose_name='Usual number of days after shipping until delivery')),
                ('estimated_delivery_max_days', models.PositiveIntegerField(default=25, verbose_name='Maximum number of days after shipping until delivery')),
            ],
            options={
                'db_table': 'tieredweightzone_carrier',
            },
        ),
        migrations.CreateModel(
            name='CarrierTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagecode', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=50, verbose_name='Carrier')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('method', models.CharField(help_text='i.e. US Mail', max_length=200, verbose_name='Method')),
                ('delivery', models.CharField(max_length=200, verbose_name='Delivery Days')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tieredweightzone.Carrier')),
            ],
            options={
                'db_table': 'tieredweightzone_carriertranslation',
                'ordering': ('languagecode', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShippingDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(verbose_name='Percentage Discount')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Order Value')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_discount', to='tieredweightzone.Carrier')),
            ],
            options={
                'db_table': 'tieredweightzone_shippingdiscount',
            },
        ),
        migrations.CreateModel(
            name='WeightTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, help_text='The minumum weight for this tier to apply', max_digits=10, verbose_name='Min Weight')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shipping Price')),
                ('expires', models.DateField(blank=True, null=True, verbose_name='Expires')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='tieredweightzone.Carrier')),
            ],
            options={
                'db_table': 'tieredweightzone_weighttier',
                'ordering': ('zone', 'carrier', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(verbose_name='Key')),
                ('continent', models.ManyToManyField(db_table='tieredweightzone_zone_continent', related_name='continent', to='l10n.Continent')),
                ('country', models.ManyToManyField(blank=True, db_table='tieredweightzone_zone_country', related_name='zone', to='l10n.Country')),
            ],
            options={
                'db_table': 'tieredweightzone_zone',
            },
        ),
        migrations.CreateModel(
            name='ZoneTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagecode', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=50, verbose_name='Zone')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tieredweightzone.Zone')),
            ],
            options={
                'db_table': 'tieredweightzone_zonetranslation',
                'ordering': ('languagecode', 'name'),
            },
        ),
        migrations.AddField(
            model_name='weighttier',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='tieredweightzone.Zone'),
        ),
        migrations.AddField(
            model_name='shippingdiscount',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_discount', to='tieredweightzone.Zone'),
        ),
    ]
