# Generated by Django 2.1.7 on 2019-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieredweightzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='delivery',
            field=models.CharField(default='', max_length=200, verbose_name='Delivery Days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='method',
            field=models.CharField(default='', help_text='i.e. US Mail', max_length=200, verbose_name='Method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Carrier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Zone'),
            preserve_default=False,
        ),
    ]
