# Generated by Django 2.1.7 on 2019-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsell', '0002_auto_20180519_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsell',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
