# Generated by Django 2.1.7 on 2019-04-29 20:02

from django.db import migrations


def reduce_translations(apps, schema_editor):
    Upsell = apps.get_model("upsell", "Upsell")
    for upsell in Upsell.objects.all():
        translation = upsell.translations.filter(active=True).first()
        if translation:
            if translation.name:
                upsell.name = translation.name
            upsell.save()


class Migration(migrations.Migration):

    dependencies = [("upsell", "0003_upsell_description")]

    operations = [migrations.RunPython(reduce_translations)]
