# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcertificate', '0003_auto_20150207_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
