# Generated by Django 2.1.7 on 2019-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcertificate', '0004_auto_20180519_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcertificate',
            name='site',
        ),
    ]
