# Generated by Django 2.0.5 on 2018-05-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Distributor', 'Distributor')], max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('In Person', 'In Person')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer'), ('Customer', 'Customer')], max_length=30, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('Company', 'Company'), ('Government', 'Government'), ('Non-profit', 'Non-profit')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Home', 'Home'), ('Fax', 'Fax'), ('Mobile', 'Mobile')], max_length=20, verbose_name='Description'),
        ),
    ]
